# Generated by Django 5.1.3 on 2024-11-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUser', '0004_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='media/ids/'),
        ),
    ]
